
version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile.mobile
    ports:
      - "19000:19000"
  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile.admin
    ports:
      - "3000:3000"
